bin_PROGRAMS = main http_server
main_SOURCES = main.cpp solution.cpp solution.h
http_server_SOURCES = HTTP_Server.cpp solution.cpp solution.h

check_PROGRAMS = test_solution test_server
test_solution_SOURCES = test_solution.cpp solution.cpp solution.h
test_server_SOURCES = test_server.cpp solution.cpp solution.h

dist_doc_DATA = README.md LICENSE
