name: Automake CI

on:
  push:
    branches:
      - branchAutomake
  pull_request:
    branches:
      - branchAutomake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y automake autoconf g++

    - name: Generate build system
      run: |
        autoreconf --install
        ./configure

    - name: Build the project
      run: make

    - name: Create tarball distribution
      run: make dist

    - name: Upload tarball artifact
      uses: actions/upload-artifact@v3
      with:
        name: project-tarball
        path: *.tar.gz
